train:
  num_workers: 16
  batch_size: 256
  adam:
    lr: 0.0001
    weight_decay: 0.00001
data:
  train_file: "data/conll2003/train.txt"
  val_file: "data/conll2003/val.txt"
  test_file: "data/conll2003/test.txt"
  word_vocab_file: "artifacts/bilstm_crf/conll2003_word_vocab.txt"
  char_vocab_file: "artifacts/bilstm_crf/conll2003_char_vocab.txt"
  label_vocab_file: "artifacts/bilstm_crf/conll2003_label_vocab.txt"
model:
  word_embedding_dim: 300
  hidden_size: 128
  rnn_type: "LSTM"
  num_layers: 1
  dropout: 0.0