train:
  num_workers: 16
  batch_size: 32
  adam:
    lr: 0.0001
    weight_decay: 0.00001
data:
  train_file: "data/conll2003/train.txt"
  val_file: "data/conll2003/val.txt"
  test_file: "data/conll2003/test.txt"
  word_vocab_file: "artifacts/bilstm_crf/conll2003_word_vocab.txt"
  char_vocab_file: "artifacts/bilstm_crf/conll2003_char_vocab.txt"
  label_vocab_file: "artifacts/bilstm_crf/conll2003_label_vocab.txt"
model:
  word_embedding_dim: 300
  word_rnn:
    rnn_type: "LSTM"
    hidden_size: 128
    num_layers: 1
    dropout: 0.0
  use_char: True
  char_embedding_dim: 30 # put 0 if use_char = False
  char_encoder_type: "RNN" # RNN or CNN
  char_rnn:
    rnn_type: "LSTM"
    hidden_size: 128
    num_layers: 1
    dropout: 0.0