train:
  num_workers: 16
  batch_size: 32
  adam:
    lr: 0.0005
    weight_decay: 0 # 0.000001
data:
  train_file: "data/ontonotes/train.txt"
  val_file: "data/ontonotes/val.txt"
  test_file: "data/ontonotes/test.txt"
  word_vocab_file: "artifacts/bilstm_crf/ontonotes_word_vocab.txt"
  char_vocab_file: "artifacts/bilstm_crf/ontonotes_char_vocab.txt"
  label_vocab_file: "artifacts/bilstm_crf/ontonotes_label_vocab.txt"
model:
  word_embedding_dim: 300
  hidden_size: 128
  rnn_type: "LSTM"
  num_layers: 1
  dropout: 0.0